// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SYSMAINMENU_H
#define UI_SYSMAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SYSMAINMENU
extern void ui_SYSMAINMENU_screen_init(void);
extern void ui_SYSMAINMENU_screen_destroy(void);
extern lv_obj_t *ui_SYSMAINMENU;
extern lv_obj_t *ui_Title1;
extern void ui_event_btniniciar( lv_event_t * e);
extern lv_obj_t *ui_btniniciar;
extern lv_obj_t *ui_lblbtnIniciar;
extern void ui_event_btnontinuar( lv_event_t * e);
extern lv_obj_t *ui_btnontinuar;
extern lv_obj_t *ui_lblbtnContinuar;
// CUSTOM VARIABLES
extern lv_obj_t *uic_btniniciar;
extern lv_obj_t *uic_lblbtnIniciar;
extern lv_obj_t *uic_btnontinuar;
extern lv_obj_t *uic_lblbtnContinuar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

