// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BTNGUARDAR_H
#define _UI_COMP_BTNGUARDAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btnGuardar
#define UI_COMP_BTNGUARDAR_BTNGUARDAR 0
#define UI_COMP_BTNGUARDAR_LBLBTNGUARDAR 1
#define _UI_COMP_BTNGUARDAR_NUM 2
lv_obj_t *ui_btnGuardar_create(lv_obj_t *comp_parent);
void ui_event_comp_btnGuardar_btnGuardar( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
