// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_btnretomar_btnretomar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_btnretomar = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      continueSavedGame( e );
}
}

// COMPONENT btnretomar

lv_obj_t *ui_btnretomar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_btnretomar;
cui_btnretomar = lv_btn_create(comp_parent);
lv_obj_set_width( cui_btnretomar, 100);
lv_obj_set_height( cui_btnretomar, 13);
lv_obj_set_x( cui_btnretomar, 0 );
lv_obj_set_y( cui_btnretomar, 9 );
lv_obj_set_align( cui_btnretomar, LV_ALIGN_CENTER );
lv_obj_add_state( cui_btnretomar, LV_STATE_USER_1 | LV_STATE_USER_2 );     /// States
lv_obj_add_flag( cui_btnretomar, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_btnretomar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_lblbtnRetomar;
cui_lblbtnRetomar = lv_label_create(cui_btnretomar);
lv_obj_set_width( cui_lblbtnRetomar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_lblbtnRetomar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_lblbtnRetomar, LV_ALIGN_CENTER );
lv_label_set_text(cui_lblbtnRetomar,"Continuar");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNRETOMAR_NUM);
children[UI_COMP_BTNRETOMAR_BTNRETOMAR] = cui_btnretomar;
children[UI_COMP_BTNRETOMAR_LBLBTNRETOMAR] = cui_lblbtnRetomar;
lv_obj_add_event_cb(cui_btnretomar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_btnretomar, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_btnretomar, ui_event_comp_btnretomar_btnretomar, LV_EVENT_ALL, children);
ui_comp_btnretomar_create_hook(cui_btnretomar);
return cui_btnretomar; 
}

