// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BTNRETOMAR_H
#define _UI_COMP_BTNRETOMAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btnretomar
#define UI_COMP_BTNRETOMAR_BTNRETOMAR 0
#define UI_COMP_BTNRETOMAR_LBLBTNRETOMAR 1
#define _UI_COMP_BTNRETOMAR_NUM 2
lv_obj_t *ui_btnretomar_create(lv_obj_t *comp_parent);
void ui_event_comp_btnretomar_btnretomar( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
