// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT PauseTitle

lv_obj_t *ui_PauseTitle_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_PauseTitle;
cui_PauseTitle = lv_textarea_create(comp_parent);
lv_obj_set_width( cui_PauseTitle, 128);
lv_obj_set_height( cui_PauseTitle, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( cui_PauseTitle, 0 );
lv_obj_set_y( cui_PauseTitle, -54 );
lv_obj_set_align( cui_PauseTitle, LV_ALIGN_CENTER );
lv_textarea_set_text(cui_PauseTitle,"GAME PAUSED");
lv_textarea_set_placeholder_text(cui_PauseTitle,"Placeholder...");
lv_textarea_set_one_line(cui_PauseTitle,true);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PAUSETITLE_NUM);
children[UI_COMP_PAUSETITLE_PAUSETITLE] = cui_PauseTitle;
lv_obj_add_event_cb(cui_PauseTitle, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_PauseTitle, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_PauseTitle_create_hook(cui_PauseTitle);
return cui_PauseTitle; 
}

