// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "synchronization.h"

void startNewGame(lv_event_t * e)
{
	// Enviar evento para iniciar nuevo juego
	event_id_t event = SE_START_NEW_GAME;
	xQueueSend(qEvents, &event, 0);
}

void continueSavedGame(lv_event_t * e)
{
	// Enviar evento para continuar juego guardado
	event_id_t event = SE_START_SAVED_GAME;
	xQueueSend(qEvents, &event, 0);
}

void resumeGame(lv_event_t * e)
{
	// Your code here
}

void saveCurrentGame(lv_event_t * e)
{
	// Your code here
}

void exitToMenu(lv_event_t * e)
{
	// Your code here
}
