/*  test_icon.c  ----------------------------------------------------------*/
#include "test_icon.h"

/*  Colores de comodidad */
#define RED   0xF800u
#define GREEN 0x07E0u
#define BLUE  0x001Fu
#define WHITE 0xFFFFu

/* 16 x 16 = 256 píxeles */
static const uint16_t test_icon_map[16 * 16] = {
/* y0 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y1 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y2 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y3 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y4 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y5 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y6 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y7 */  RED,RED,RED,RED,RED,RED,RED,RED,  BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
/* y8 */  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y9 */  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y10*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y11*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y12*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y13*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y14*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
/* y15*/  GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,  WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
};

const lv_img_dsc_t test_icon_16x16 = {
    .header.always_zero = 0,
    .header.w = 16,
    .header.h = 16,
    .header.cf = LV_IMG_CF_TRUE_COLOR,   /* RGB565 */
    .data_size = sizeof(test_icon_map),
    .data = (const uint8_t *)test_icon_map
};
