// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SYSPAUSED_H
#define UI_SYSPAUSED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SYSPAUSED
extern void ui_SYSPAUSED_screen_init(void);
extern void ui_SYSPAUSED_screen_destroy(void);
extern lv_obj_t *ui_SYSPAUSED;
extern lv_obj_t *ui_Title2;
extern void ui_event_btnRetomar( lv_event_t * e);
extern lv_obj_t *ui_btnRetomar;
extern lv_obj_t *ui_lblbtnRetomar2;
extern void ui_event_btnGuardar( lv_event_t * e);
extern lv_obj_t *ui_btnGuardar;
extern lv_obj_t *ui_lblbtnGuardar1;
extern void ui_event_btnSalir( lv_event_t * e);
extern lv_obj_t *ui_btnSalir;
extern lv_obj_t *ui_lblbtnSalir;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SYSPAUSED;
extern lv_obj_t *uic_btnRetomar;
extern lv_obj_t *uic_btnGuardar;
extern lv_obj_t *uic_btnSalir;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

