// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_btnGuardar_btnGuardar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_btnGuardar = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      saveCurrentGame( e );
}
}

// COMPONENT btnGuardar

lv_obj_t *ui_btnGuardar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_btnGuardar;
cui_btnGuardar = lv_btn_create(comp_parent);
lv_obj_set_width( cui_btnGuardar, 100);
lv_obj_set_height( cui_btnGuardar, 12);
lv_obj_set_x( cui_btnGuardar, 1 );
lv_obj_set_y( cui_btnGuardar, -10 );
lv_obj_set_align( cui_btnGuardar, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_btnGuardar, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

lv_obj_t *cui_lblbtnGuardar;
cui_lblbtnGuardar = lv_label_create(cui_btnGuardar);
lv_obj_set_width( cui_lblbtnGuardar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_lblbtnGuardar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_lblbtnGuardar, LV_ALIGN_CENTER );
lv_label_set_text(cui_lblbtnGuardar,"Guardar");
lv_obj_add_state( cui_lblbtnGuardar, LV_STATE_USER_1 );     /// States

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNGUARDAR_NUM);
children[UI_COMP_BTNGUARDAR_BTNGUARDAR] = cui_btnGuardar;
children[UI_COMP_BTNGUARDAR_LBLBTNGUARDAR] = cui_lblbtnGuardar;
lv_obj_add_event_cb(cui_btnGuardar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_btnGuardar, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_btnGuardar, ui_event_comp_btnGuardar_btnGuardar, LV_EVENT_ALL, children);
ui_comp_btnGuardar_create_hook(cui_btnGuardar);
return cui_btnGuardar; 
}

