// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_lblbtnContinuar;
lv_obj_t *uic_btnontinuar;
lv_obj_t *uic_lblbtnIniciar;
lv_obj_t *uic_btniniciar;
lv_obj_t *ui_SYSMAINMENU = NULL;lv_obj_t *ui_Title1 = NULL;lv_obj_t *ui_btniniciar = NULL;lv_obj_t *ui_lblbtnIniciar = NULL;lv_obj_t *ui_btnontinuar = NULL;lv_obj_t *ui_lblbtnContinuar = NULL;
// event funtions
void ui_event_btniniciar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      startNewGame( e );
}
}

void ui_event_btnontinuar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      continueSavedGame( e );
}
}

// build funtions

void ui_SYSMAINMENU_screen_init(void)
{
ui_SYSMAINMENU = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SYSMAINMENU, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Title1 = lv_textarea_create(ui_SYSMAINMENU);
lv_obj_set_width( ui_Title1, 118);
lv_obj_set_height( ui_Title1, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Title1, 0 );
lv_obj_set_y( ui_Title1, -54 );
lv_obj_set_align( ui_Title1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_Title1,"RETRO_GAME");
lv_textarea_set_placeholder_text(ui_Title1,"Placeholder...");
lv_textarea_set_one_line(ui_Title1,true);

ui_btniniciar = lv_btn_create(ui_SYSMAINMENU);
lv_obj_set_width( ui_btniniciar, 100);
lv_obj_set_height( ui_btniniciar, 27);
lv_obj_set_x( ui_btniniciar, 1 );
lv_obj_set_y( ui_btniniciar, -10 );
lv_obj_set_align( ui_btniniciar, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_btniniciar, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_lblbtnIniciar = lv_label_create(ui_btniniciar);
lv_obj_set_width( ui_lblbtnIniciar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbtnIniciar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbtnIniciar, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbtnIniciar,"Nuevo Juego");
lv_obj_add_state( ui_lblbtnIniciar, LV_STATE_USER_1 );     /// States

ui_btnontinuar = lv_btn_create(ui_SYSMAINMENU);
lv_obj_set_width( ui_btnontinuar, 100);
lv_obj_set_height( ui_btnontinuar, 28);
lv_obj_set_x( ui_btnontinuar, 0 );
lv_obj_set_y( ui_btnontinuar, 29 );
lv_obj_set_align( ui_btnontinuar, LV_ALIGN_CENTER );
lv_obj_add_state( ui_btnontinuar, LV_STATE_USER_2 | LV_STATE_USER_3 );     /// States
lv_obj_add_flag( ui_btnontinuar, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnontinuar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblbtnContinuar = lv_label_create(ui_btnontinuar);
lv_obj_set_width( ui_lblbtnContinuar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbtnContinuar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbtnContinuar, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbtnContinuar,"Continuar");

lv_obj_add_event_cb(ui_btniniciar, ui_event_btniniciar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnontinuar, ui_event_btnontinuar, LV_EVENT_ALL, NULL);
uic_btniniciar = ui_btniniciar;
uic_lblbtnIniciar = ui_lblbtnIniciar;
uic_btnontinuar = ui_btnontinuar;
uic_lblbtnContinuar = ui_lblbtnContinuar;

}

void ui_SYSMAINMENU_screen_destroy(void)
{
   if (ui_SYSMAINMENU) lv_obj_del(ui_SYSMAINMENU);

// NULL screen variables
ui_SYSMAINMENU= NULL;
ui_Title1= NULL;
uic_btniniciar= NULL;
ui_btniniciar= NULL;
uic_lblbtnIniciar= NULL;
ui_lblbtnIniciar= NULL;
uic_btnontinuar= NULL;
ui_btnontinuar= NULL;
uic_lblbtnContinuar= NULL;
ui_lblbtnContinuar= NULL;

}
