// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../lv_port/lv_port_indev.h"

lv_obj_t *uic_lblbtnContinuar;
lv_obj_t *uic_btnontinuar;
lv_obj_t *uic_lblbtnIniciar;
lv_obj_t *uic_btniniciar;
lv_obj_t *ui_SYSMAINMENU = NULL;lv_obj_t *ui_Title1 = NULL;lv_obj_t *ui_btniniciar = NULL;lv_obj_t *ui_lblbtnIniciar = NULL;lv_obj_t *ui_btnontinuar = NULL;lv_obj_t *ui_lblbtnContinuar = NULL;

static void sysmain_loaded_cb(lv_event_t * e)
{
    lv_group_t * g = lv_port_indev_get_group();
    if(!g) return;

    lv_group_remove_all_objs(g);
    lv_group_add_obj(g, ui_btnontinuar);   /* orden inverso */
    lv_group_add_obj(g, ui_btniniciar);

    lv_group_focus_obj(ui_btniniciar);     /* foco final   */
    lv_group_focus_freeze(g, false);       /* un-freeze    */
}

// event funtions
void ui_event_btniniciar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_KEY) {
        uint32_t key = lv_event_get_key(e);
        if (key == LV_KEY_ENTER) {
            /* Button A pressed while this button is focused */
            /* TODO: Implement startNewGame logic */
            // startNewGame( e );
            /* Provisional: Switch to SYSPAUSED screen for testing */
            _ui_screen_change(&ui_SYSPAUSED, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, ui_SYSPAUSED_screen_init);
        }
    }
}

void ui_event_btnontinuar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_KEY) {
        uint32_t key = lv_event_get_key(e);
        if (key == LV_KEY_ENTER) {
            /* Button A pressed while this button is focused */
            /* TODO: Implement continueSavedGame logic */
            // continueSavedGame( e );
            /* Provisional: Switch to SYSPAUSED screen for testing */
            _ui_screen_change(&ui_SYSPAUSED, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, ui_SYSPAUSED_screen_init);
        }
    }
}

// build funtions

void ui_SYSMAINMENU_screen_init(void)
{
    ui_SYSMAINMENU = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_SYSMAINMENU, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Title1 = lv_label_create(ui_SYSMAINMENU);
    lv_obj_set_width( ui_Title1, LV_SIZE_CONTENT);
    lv_obj_set_height( ui_Title1, LV_SIZE_CONTENT);   
    lv_obj_set_x( ui_Title1, 0 );
    lv_obj_set_y( ui_Title1, -54 );
    lv_obj_set_align( ui_Title1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Title1,"RETRO_GAME");

    ui_btniniciar = lv_btn_create(ui_SYSMAINMENU);
    lv_obj_set_width( ui_btniniciar, 100);
    lv_obj_set_height( ui_btniniciar, 27);
    lv_obj_set_x( ui_btniniciar, 1 );
    lv_obj_set_y( ui_btniniciar, -10 );
    lv_obj_set_align( ui_btniniciar, LV_ALIGN_CENTER );

    ui_lblbtnIniciar = lv_label_create(ui_btniniciar);
    lv_obj_set_align( ui_lblbtnIniciar, LV_ALIGN_CENTER );
    lv_label_set_text(ui_lblbtnIniciar,"Nuevo Juego");

    ui_btnontinuar = lv_btn_create(ui_SYSMAINMENU);
    lv_obj_set_width( ui_btnontinuar, 100);
    lv_obj_set_height( ui_btnontinuar, 28);
    lv_obj_set_x( ui_btnontinuar, 0 );
    lv_obj_set_y( ui_btnontinuar, 29 );
    lv_obj_set_align( ui_btnontinuar, LV_ALIGN_CENTER );

    ui_lblbtnContinuar = lv_label_create(ui_btnontinuar);
    lv_obj_set_align( ui_lblbtnContinuar, LV_ALIGN_CENTER );
    lv_label_set_text(ui_lblbtnContinuar,"Continuar");

    lv_obj_add_event_cb(ui_btniniciar, ui_event_btniniciar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnontinuar, ui_event_btnontinuar, LV_EVENT_ALL, NULL);

    /* Add buttons to input group for joystick navigation (in reverse visual order to fix UP/DOWN) */
    lv_group_t * input_group = lv_port_indev_get_group();
    if(input_group != NULL) {
        /* Clear any previous objects from the group */
        lv_group_remove_all_objs(input_group);
        
        lv_group_add_obj(input_group, ui_btnontinuar);    /* Add "Continuar" button (bottom) first */
        lv_group_add_obj(input_group, ui_btniniciar);     /* Add "Nuevo Juego" button (top) last */
        /* Note: ui_Title1 (label) is intentionally NOT added to the group */
        
        /* Set initial focus on the first button (Nuevo Juego - top button) */
        lv_group_focus_obj(ui_btniniciar);
    }

    uic_btniniciar = ui_btniniciar;
    uic_lblbtnIniciar = ui_lblbtnIniciar;
    uic_btnontinuar = ui_btnontinuar;
    uic_lblbtnContinuar = ui_lblbtnContinuar;

    lv_obj_add_event_cb(ui_SYSMAINMENU,
                        sysmain_loaded_cb,
                        LV_EVENT_SCREEN_LOADED, NULL);

}

void ui_SYSMAINMENU_screen_destroy(void)
{
   if (ui_SYSMAINMENU) lv_obj_del(ui_SYSMAINMENU);

// NULL screen variables
ui_SYSMAINMENU= NULL;
ui_Title1= NULL;
uic_btniniciar= NULL;
ui_btniniciar= NULL;
uic_lblbtnIniciar= NULL;
ui_lblbtnIniciar= NULL;
uic_btnontinuar= NULL;
ui_btnontinuar= NULL;
uic_lblbtnContinuar= NULL;
ui_lblbtnContinuar= NULL;

}
