// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_btnSalir;
lv_obj_t *uic_btnGuardar;
lv_obj_t *uic_btnRetomar;
lv_obj_t *uic_SYSPAUSED;
lv_obj_t *ui_SYSPAUSED = NULL;lv_obj_t *ui_Title2 = NULL;lv_obj_t *ui_btnRetomar = NULL;lv_obj_t *ui_lblbtnRetomar2 = NULL;lv_obj_t *ui_btnGuardar = NULL;lv_obj_t *ui_lblbtnGuardar1 = NULL;lv_obj_t *ui_btnSalir = NULL;lv_obj_t *ui_lblbtnSalir = NULL;
// event funtions
void ui_event_btnRetomar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      resumeGame( e );
}
}

void ui_event_btnGuardar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      saveCurrentGame( e );
}
}

void ui_event_btnSalir( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      exitToMenu( e );
}
}

// build funtions

void ui_SYSPAUSED_screen_init(void)
{
ui_SYSPAUSED = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SYSPAUSED, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_SYSPAUSED, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SYSPAUSED);

ui_Title2 = lv_textarea_create(ui_SYSPAUSED);
lv_obj_set_width( ui_Title2, 128);
lv_obj_set_height( ui_Title2, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Title2, 0 );
lv_obj_set_y( ui_Title2, -54 );
lv_obj_set_align( ui_Title2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_Title2,"GAME PAUSED");
lv_textarea_set_placeholder_text(ui_Title2,"Placeholder...");
lv_textarea_set_one_line(ui_Title2,true);

ui_btnRetomar = lv_btn_create(ui_SYSPAUSED);
lv_obj_set_width( ui_btnRetomar, 100);
lv_obj_set_height( ui_btnRetomar, 21);
lv_obj_set_x( ui_btnRetomar, 0 );
lv_obj_set_y( ui_btnRetomar, 33 );
lv_obj_set_align( ui_btnRetomar, LV_ALIGN_CENTER );
lv_obj_add_state( ui_btnRetomar, LV_STATE_USER_1 | LV_STATE_USER_2 );     /// States
lv_obj_add_flag( ui_btnRetomar, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnRetomar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblbtnRetomar2 = lv_label_create(ui_btnRetomar);
lv_obj_set_width( ui_lblbtnRetomar2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbtnRetomar2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbtnRetomar2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbtnRetomar2,"Continuar");

ui_btnGuardar = lv_btn_create(ui_SYSPAUSED);
lv_obj_set_width( ui_btnGuardar, 100);
lv_obj_set_height( ui_btnGuardar, 18);
lv_obj_set_x( ui_btnGuardar, 1 );
lv_obj_set_y( ui_btnGuardar, -14 );
lv_obj_set_align( ui_btnGuardar, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_btnGuardar, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_lblbtnGuardar1 = lv_label_create(ui_btnGuardar);
lv_obj_set_width( ui_lblbtnGuardar1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbtnGuardar1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbtnGuardar1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbtnGuardar1,"Guardar");
lv_obj_add_state( ui_lblbtnGuardar1, LV_STATE_USER_1 );     /// States

ui_btnSalir = lv_btn_create(ui_SYSPAUSED);
lv_obj_set_width( ui_btnSalir, 100);
lv_obj_set_height( ui_btnSalir, 17);
lv_obj_set_x( ui_btnSalir, 0 );
lv_obj_set_y( ui_btnSalir, 9 );
lv_obj_set_align( ui_btnSalir, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnSalir, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSalir, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblbtnSalir = lv_label_create(ui_btnSalir);
lv_obj_set_width( ui_lblbtnSalir, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbtnSalir, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbtnSalir, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbtnSalir,"Salir");

lv_obj_add_event_cb(ui_btnRetomar, ui_event_btnRetomar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnGuardar, ui_event_btnGuardar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnSalir, ui_event_btnSalir, LV_EVENT_ALL, NULL);
uic_SYSPAUSED = ui_SYSPAUSED;
uic_btnRetomar = ui_btnRetomar;
uic_btnGuardar = ui_btnGuardar;
uic_btnSalir = ui_btnSalir;

}

void ui_SYSPAUSED_screen_destroy(void)
{
   if (ui_SYSPAUSED) lv_obj_del(ui_SYSPAUSED);

// NULL screen variables
uic_SYSPAUSED= NULL;
ui_SYSPAUSED= NULL;
ui_Title2= NULL;
uic_btnRetomar= NULL;
ui_btnRetomar= NULL;
ui_lblbtnRetomar2= NULL;
uic_btnGuardar= NULL;
ui_btnGuardar= NULL;
ui_lblbtnGuardar1= NULL;
uic_btnSalir= NULL;
ui_btnSalir= NULL;
ui_lblbtnSalir= NULL;

}
