// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../lv_port/lv_port_indev.h"

lv_obj_t *uic_btnSalir;
lv_obj_t *uic_btnGuardar;
lv_obj_t *uic_btnRetomar;
lv_obj_t *uic_SYSPAUSED;
lv_obj_t *ui_SYSPAUSED = NULL;lv_obj_t *ui_Title2 = NULL;lv_obj_t *ui_btnRetomar = NULL;lv_obj_t *ui_lblbtnRetomar2 = NULL;lv_obj_t *ui_btnGuardar = NULL;lv_obj_t *ui_lblbtnGuardar1 = NULL;lv_obj_t *ui_btnSalir = NULL;lv_obj_t *ui_lblbtnSalir = NULL;

static void sysmain_loaded_cb(lv_event_t * e)
{
    lv_group_t * g = lv_port_indev_get_group();
    if(!g) return;

    lv_group_remove_all_objs(g);
    lv_group_add_obj(g, ui_btnSalir);   /* orden inverso */
    lv_group_add_obj(g, ui_btnGuardar);
    lv_group_add_obj(g, ui_btnRetomar);

    lv_group_focus_obj(ui_btnRetomar);     /* foco final   */
    lv_group_focus_freeze(g, false);       /* un-freeze    */
}

// event funtions
void ui_event_btnRetomar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_KEY) {
        uint32_t key = lv_event_get_key(e);
        if (key == LV_KEY_ENTER) {
            /* Button A pressed while this button is focused */
            /* TODO: Implement resumeGame logic */
            // resumeGame( e );
        }
    }
}

void ui_event_btnGuardar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_KEY) {
        uint32_t key = lv_event_get_key(e);
        if (key == LV_KEY_ENTER) {
            /* Button A pressed while this button is focused */
            /* TODO: Implement saveCurrentGame logic */
            // saveCurrentGame( e );
        }
    }
}

void ui_event_btnSalir( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_KEY) {
        uint32_t key = lv_event_get_key(e);
        if (key == LV_KEY_ENTER) {
            /* Button A pressed while this button is focused */
            /* Provisional: Switch back to SYSMAINMENU for testing */
            lv_group_t * g = lv_port_indev_get_group();
            if(g) lv_group_focus_freeze(g, true);
            _ui_screen_change(&ui_SYSMAINMENU, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, ui_SYSMAINMENU_screen_init);
        }
    }
}

// build funtions

void ui_SYSPAUSED_screen_init(void)
{
    ui_SYSPAUSED = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_SYSPAUSED, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_add_event_cb(ui_SYSPAUSED, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SYSPAUSED);

    ui_Title2 = lv_label_create(ui_SYSPAUSED);
    lv_obj_set_width( ui_Title2, LV_SIZE_CONTENT);
    lv_obj_set_height( ui_Title2, LV_SIZE_CONTENT);   
    lv_obj_set_x( ui_Title2, 0 );
    lv_obj_set_y( ui_Title2, -54 );
    lv_obj_set_align( ui_Title2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Title2,"GAME PAUSED");

    /* First button: Continuar (top) */
    ui_btnRetomar = lv_btn_create(ui_SYSPAUSED);
    lv_obj_set_width( ui_btnRetomar, 100);
    lv_obj_set_height( ui_btnRetomar, 25);
    lv_obj_set_x( ui_btnRetomar, 0 );
    lv_obj_set_y( ui_btnRetomar, -15 );
    lv_obj_set_align( ui_btnRetomar, LV_ALIGN_CENTER );

    ui_lblbtnRetomar2 = lv_label_create(ui_btnRetomar);
    lv_obj_set_align( ui_lblbtnRetomar2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_lblbtnRetomar2,"Continuar");

    /* Second button: Guardar (middle) */
    ui_btnGuardar = lv_btn_create(ui_SYSPAUSED);
    lv_obj_set_width( ui_btnGuardar, 100);
    lv_obj_set_height( ui_btnGuardar, 25);
    lv_obj_set_x( ui_btnGuardar, 0 );
    lv_obj_set_y( ui_btnGuardar, 15 );
    lv_obj_set_align( ui_btnGuardar, LV_ALIGN_CENTER );

    ui_lblbtnGuardar1 = lv_label_create(ui_btnGuardar);
    lv_obj_set_align( ui_lblbtnGuardar1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_lblbtnGuardar1,"Guardar");

    /* Third button: Salir (bottom) */
    ui_btnSalir = lv_btn_create(ui_SYSPAUSED);
    lv_obj_set_width( ui_btnSalir, 100);
    lv_obj_set_height( ui_btnSalir, 25);
    lv_obj_set_x( ui_btnSalir, 0 );
    lv_obj_set_y( ui_btnSalir, 45 );
    lv_obj_set_align( ui_btnSalir, LV_ALIGN_CENTER );

    ui_lblbtnSalir = lv_label_create(ui_btnSalir);
    lv_obj_set_align( ui_lblbtnSalir, LV_ALIGN_CENTER );
    lv_label_set_text(ui_lblbtnSalir,"Salir");

    lv_obj_add_event_cb(ui_btnRetomar, ui_event_btnRetomar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGuardar, ui_event_btnGuardar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSalir, ui_event_btnSalir, LV_EVENT_ALL, NULL);

    /* Add buttons to input group for joystick navigation (in reverse visual order to fix UP/DOWN) */
    lv_group_t * input_group = lv_port_indev_get_group();
    if(input_group != NULL) {
        /* Clear any previous objects from the group */
        lv_group_remove_all_objs(input_group);
        
        lv_group_add_obj(input_group, ui_btnSalir);      /* Add "Salir" button (bottom) first */
        lv_group_add_obj(input_group, ui_btnGuardar);    /* Add "Guardar" button (middle) second */
        lv_group_add_obj(input_group, ui_btnRetomar);    /* Add "Continuar" button (top) last */
        /* Note: ui_Title2 (label) is intentionally NOT added to the group */
        
        /* Set initial focus on the first button (Continuar - top button) */
        lv_group_focus_obj(ui_btnRetomar);
    }

    uic_SYSPAUSED = ui_SYSPAUSED;
    uic_btnRetomar = ui_btnRetomar;
    uic_btnGuardar = ui_btnGuardar;
    uic_btnSalir = ui_btnSalir;

    lv_obj_add_event_cb(ui_SYSPAUSED,
                    sysmain_loaded_cb,
                    LV_EVENT_SCREEN_LOADED, NULL);

}

void ui_SYSPAUSED_screen_destroy(void)
{
   if (ui_SYSPAUSED) lv_obj_del(ui_SYSPAUSED);

    // NULL screen variables
    uic_SYSPAUSED= NULL;
    ui_SYSPAUSED= NULL;
    ui_Title2= NULL;
    uic_btnRetomar= NULL;
    ui_btnRetomar= NULL;
    ui_lblbtnRetomar2= NULL;
    uic_btnGuardar= NULL;
    ui_btnGuardar= NULL;
    ui_lblbtnGuardar1= NULL;
    uic_btnSalir= NULL;
    ui_btnSalir= NULL;
    ui_lblbtnSalir= NULL;

}
